---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    author: rufus
    name: result-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    author: rufus
    name: result-app-pod
...